### ISSUE TITLE
Separate "Text" section into two Sections: Text One Column and Text Two Columns

### ISSUE THREAD

**Issue by michaelburtonray** [saturdays-nyc/spree-blogging-spree#41]
Either separate the Text section into two diffarant section types or create a checkbox / integer field in order to specify 1 or 2 column text.

**Comment by michaelburtonray** [comment]
Hey @aaronzdavis as a user where in the backend would I see this?

**Comment by aaronzdavis** [comment]
@michaelburtonray When you add a text only section you'll see radio buttons below the text entry area.
